In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
# Load your dataset
df = pd.read_csv('../data/dataset.csv')

# Split the 'Services_Used' column into separate columns
services_df = df['Services_Used'].str.get_dummies(sep=',')

In [3]:
services_df.head()

,Mobile data/Internet,None of the above,SMS/Text messaging,Voice Calls,Mobile data/Internet,None of the above,SMS/Text messaging,Voice Calls
0,0,0,0,0,0,0,0,1
1,1,1,0,0,0,0,1,0
2,1,1,1,0,0,0,0,1
3,1,1,1,0,0,0,0,1
4,0,0,0,0,0,0,1,0

In [4]:

# Concatenate the original DataFrame with the services DataFrame
df = pd.concat([df, services_df], axis=1)
df

,Gender,College,Churn,Level,Residence,SIM_Usage,Usage_Freq,Network_Strength,Services_Used,Data_Exhaustion,...,Reasons_Discontinue,Monthly_Data_Usage,Mobile data/Internet,None of the above,SMS/Text messaging,Voice Calls,Mobile data/Internet,None of the above,SMS/Text messaging,Voice Calls
0,Female,School of Business,No,400,Off-campus,Yes,Occasionally,3,Voice Calls,Yes,...,"Unsatisfactory customer service, Insufficient ...",1.82,0,0,0,0,0,0,0,1
1,Male,College of Agriculture and Natural Resources,No,400,Off-campus,Yes,Daily,6,"SMS/Text messaging, Mobile data/Internet, None...",Yes,...,Insufficient data allowance,6.64,1,1,0,0,0,0,1,0
2,Female,College of Humanity and Social Science,Yes,200,On-campus,No,Several times a week,3,"Voice Calls, Mobile data/Internet, None of the...",Yes,...,"High costs/pricing, Insufficient data allowanc...",2.05,1,1,1,0,0,0,0,1
3,Male,College of Science,Yes,100,Off-campus,Yes,Daily,2,"Voice Calls, Mobile data/Internet, SMS/Text me...",No,...,High costs/pricing,8.56,1,1,1,0,0,0,0,1
4,Female,College of Humanity and Social Science,Yes,400,Off-campus,Yes,Occasionally,4,SMS/Text messaging,Yes,...,"High costs/pricing, Unsatisfactory customer se...",6.06,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,Male,College of Science,Yes,200,Off-campus,No,Several times a week,2,None of the above,Yes,...,"High costs/pricing, Insufficient data allowance",4.19,0,0,0,0,0,1,0,0
764,Male,College of Agriculture and Natural Resources,Yes,100,On-campus,No,Daily,4,"None of the above, SMS/Text messaging, Voice C...",No,...,"Unsatisfactory customer service, Insufficient ...",8.60,0,0,1,1,0,1,0,0
765,Female,College of Agriculture and Natural Resources,No,600,Off-campus,No,Daily,2,"None of the above, Mobile data/Internet",No,...,"Unsatisfactory customer service, Insufficient ...",7.54,1,0,0,0,0,1,0,0
766,Male,College of Art and Built Environment,Yes,300,Off-campus,No,Never,6,"None of the above, Voice Calls",No,...,Poor network quality/coverage,3.36,0,0,0,1,0,1,0,0
767,Female,College of Agriculture and Natural Resources,Yes,300,Off-campus,No,Occasionally,3,"Mobile data/Internet, None of the above, Voice...",No,...,"Poor network quality/coverage, Unsatisfactory ...",7.70,0,1,0,1,1,0,0,0

In [5]:


# Drop the original 'Services_Used' column
df = df.drop('Services_Used', axis=1)
df

,Gender,College,Churn,Level,Residence,SIM_Usage,Usage_Freq,Network_Strength,Data_Exhaustion,Other_Networks,Reasons_Discontinue,Monthly_Data_Usage,Mobile data/Internet,None of the above,SMS/Text messaging,Voice Calls,Mobile data/Internet,None of the above,SMS/Text messaging,Voice Calls
0,Female,School of Business,No,400,Off-campus,Yes,Occasionally,3,Yes,Yes,"Unsatisfactory customer service, Insufficient ...",1.82,0,0,0,0,0,0,0,1
1,Male,College of Agriculture and Natural Resources,No,400,Off-campus,Yes,Daily,6,Yes,Yes,Insufficient data allowance,6.64,1,1,0,0,0,0,1,0
2,Female,College of Humanity and Social Science,Yes,200,On-campus,No,Several times a week,3,Yes,Yes,"High costs/pricing, Insufficient data allowanc...",2.05,1,1,1,0,0,0,0,1
3,Male,College of Science,Yes,100,Off-campus,Yes,Daily,2,No,Yes,High costs/pricing,8.56,1,1,1,0,0,0,0,1
4,Female,College of Humanity and Social Science,Yes,400,Off-campus,Yes,Occasionally,4,Yes,Yes,"High costs/pricing, Unsatisfactory customer se...",6.06,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,Male,College of Science,Yes,200,Off-campus,No,Several times a week,2,Yes,Yes,"High costs/pricing, Insufficient data allowance",4.19,0,0,0,0,0,1,0,0
764,Male,College of Agriculture and Natural Resources,Yes,100,On-campus,No,Daily,4,No,No,"Unsatisfactory customer service, Insufficient ...",8.60,0,0,1,1,0,1,0,0
765,Female,College of Agriculture and Natural Resources,No,600,Off-campus,No,Daily,2,No,Yes,"Unsatisfactory customer service, Insufficient ...",7.54,1,0,0,0,0,1,0,0
766,Male,College of Art and Built Environment,Yes,300,Off-campus,No,Never,6,No,Yes,Poor network quality/coverage,3.36,0,0,0,1,0,1,0,0
767,Female,College of Agriculture and Natural Resources,Yes,300,Off-campus,No,Occasionally,3,No,Yes,"Poor network quality/coverage, Unsatisfactory ...",7.70,0,1,0,1,1,0,0,0

In [6]:
# Save the preprocessed data to a new CSV file
df.to_csv('preprocessed_data.csv', index=False)

In [7]:


# Assuming 'ohe_cols' is a list of columns to be one-hot encoded
ohe = OneHotEncoder()
ohe_cols =
encoded_data = ohe.fit_transform(df[ohe_cols])

NameError: name 'ohe_cols' is not defined

In [ ]:





# Convert the encoded data into a pandas DataFrame
encoded_df = pd.DataFrame(encoded_data.toarray(), columns=ohe.get_feature_names(ohe_cols))

# Concatenate the original DataFrame with the encoded DataFrame
preprocessed_df = pd.concat([df.drop(ohe_cols, axis=1), encoded_df], axis=1)

# Save the preprocessed data to a new CSV file
preprocessed_df.to_csv('../data/preprocessed_data.csv', index=False)